services:
  elasticsearch:
    image: elasticsearch:9.0.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    mem_limit: 1g
    init: true

  logstash:
    image: logstash:9.0.3
    container_name: logstash
    volumes:
      - logger-logs:/logs
    depends_on:
      - elasticsearch
      - fastify
    init: true

  kibana:
    image: kibana:9.0.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    init: true

  fastify:
    build: ./logger
    image: logger:oo
    container_name: logger
    ports:
      - "3030:3000"
    volumes:
      - logger-logs:/app/logs
    init: true

  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - "9090:9090"
    init: true

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    init: true

volumes:
  logger-logs:
