services:
  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch:oo
    container_name: elasticsearch
    ports:
      - "9200:9200"

  logstash:
    build: ./logstash
    image: logstash:oo
    container_name: logstash
    depends_on:
      - elasticsearch
