global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - prometheus:9090
    labels:
      app: prometheus

- job_name: kibana
  scrape_interval: 20s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - kibana:9200
    labels:
      app: kibana

- job_name: fastify
  scrape_interval: 25s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - logger:3030
    labels:
      app: logger

- job_name: grafana
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - grafana:3000
    labels:
      app: grafana
